# Generated by Django 3.0.6 on 2020-06-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennywoodapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='itinerary'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attractions', to='kennywoodapi.ParkArea'),
        ),
    ]
